### ISSUE TITLE
InformixAgent 'java' process is hammering the CPU of the IDS test box when SSL is enabled

### ISSUE THREAD

**Issue by jagathabhaya** [informix/informixhq-agent#10]
I have found a big issue the agent process is actually hammering the CPU in my test DB servers.

I have two test boxes currently running with 4 CPU VPs and almost all unusable after running the agent process from the last day till now. 

![top](https://user-images.githubusercontent.com/39396150/40399487-f04aa48e-5e80-11e8-90b8-c4ba8c853795.png)
![top1](https://user-images.githubusercontent.com/39396150/40399488-f07d7da0-5e80-11e8-8c26-e696daeccadf.png)

The agent is  actually a light weight process?
 No any other user processes running on these two test servers. 
Only the InformixHQ agent,   The agent running for a day caused both the database servers to be almost unusable.

Any idea?
Regards

**Comment by jagathabhaya** [comment]
FYI:
These are the current sensors running in these boxes:
![sensors](https://user-images.githubusercontent.com/39396150/40402901-a208a706-5e91-11e8-86ba-eff33efc71cc.png)

Regards

**Comment by ekuehnhausen** [comment]
Are there any errors in your agent log file?

Is the high CPU usage and high resident memory size a problem that showed up as soon as you started the agent or as soon as you enabled sensors? Or this is a problem that worsened over the course of the day?

FYI, I will leave these same sensors running on my system overnight to see what happens, but so far, in my env, I'm seeing very low CPU usage and no apparent memory leak or increased resource usage over time.

**Comment by jagathabhaya** [comment]
I could not locate the agent.log file? 
Could you please direct me where to find out as I am not using any config parameter for that log parameter?

Further, I did not notice any errors on the screen, as the agent runs as a Linux service.

The symptoms noticed over a day running  the agents.

NOTE: We have enabled SSL connectivity between HQ server  and Agent. 
Once,  I killed the agent process both the servers CPU load came back to normal.

Perhaps, this could this be due to SSL connectivity between HQ server  and Agent?

Anyway,  Today, I have reset that environment to use for my other testing as these boxes were almost unusable with the load.  If you can point out (by default) which location the agent.log file creates, hope I could dig down further during the next setup or send into you to analyse it further from your end.  
Thanks

**Comment by ekuehnhausen** [comment]
By default, the agent log messages go to the console. So you can pipe that output to a file. 

Alternatively, you can use a system property to set the log file.
`java -jar -Dorg.slf4j.simpleLogger.logFile=agent.log informixhq-agent-0.1.0.jar agent.properties`

**Comment by ekuehnhausen** [comment]
by the way, my suspicion is that this could be related to the Operating System Disk Utilization sensor. So you could also try just removing that sensor and see if that makes any difference.

**Comment by jagathabhaya** [comment]
I had a chance to look into this again and collected the log information as this can be easily reproduced by running one or two days the agent. So, the servers are almost unusable at this stage. The issue looks like to me it cannot connect to the repository database due to some issue after running few days. Unfortunately, there is no date time  stamp in the log file. So, I cannot clearly say when the issue starts happening. NOTE: This agent log file is the local agent file , recorded the information. Can you please look at the log file attached (It is big) , and see whether you can identify some thing there as the initial symptom?
NOTE: If I try with 'dbaccess' although the system is slow currently  I can access database and all the tables.
Let me know, if you need further detail about the setup ect... As we can easily reproduce this by establishing the server and agent back. 

[agent_file_log.zip](https://github.com/informix/informixhq-agent/files/2043035/agent_file_log.zip)

Cheers

**Comment by jagathabhaya** [comment]
As you pointed out earlier, Could this issue be related to the Disk I/O ?

I can see following error lines printed on regular basis in my provided log file:

Repeating the same error over a day on Disk I/O could be caused to accumulate the CPU usage of the server?
------------------------------
[Monitor-os_diskio] INFO com.informix.hq.agent.Monitor - Checking metric: Operat
ing System Disk I/O
[Monitor-os_diskio] ERROR com.informix.hq.agent.os.LinuxProcDiskStats - Could no
t parse disk I/O info out of /proc/diskstats

Regards

**Comment by ekuehnhausen** [comment]
Your log file does help.

Today, I put in a fix to the agent that should address the "could not parse disko IO info" errors that you are seeing. I've also made a change to configure the SLF4J simple logger to include timestamps by default.

But I'm still trying to figure out why it is running your machine out of CPU resources. I don't see how those disk I/O parsing errors would do that. I do wonder if the timeout errors trying to connect to the repository database at the end are because the machine is already swamped CPU wise, making those connection errors more of a symptom than a cause. Anyway, still looking into this part of the problem.

**Comment by jagathabhaya** [comment]
Thanks a lot for your support with this.
If I can download the fix,  and see whether that could help us to overcome the issue reported or not.

Has this fix been available to be downloaded through the same GitHub link now ?

BTW: After enabling considerable number of sensors, I could see server is generating Logical log files continuously. 
To avoid happening that type of situation , Does 'InformixHQ' support no-logging database concept to setup the repository database ?

Kind Regards

**Comment by jagathabhaya** [comment]
Thanks for the reply.

Every test box we try to setup InformixHQ,  we could notice the similar symptoms. 
Initial start of the sensor setting used maximum 2% of CPU which is ok for us, however,  keep  running for a day become the server almost unusable for us. I tried the setup yesterday in a different box and when I check it in today morning , it is running with nearly 100% CPU using for that java file without any users or load in the system. No errors , I noticed with it.
So,  till we identify the issue and have a proper fix for this, InformixHQ tool is almost unusable to implement in any production machine in our production environments.

I have attached another round of some diagnostic files , to see whether you could have some thing pointed out as a clue for us.

Let me know, any other way of diagnosing the issue or need any other detail from my side. 

BTW: Can you setup a test case with SSL enable between server and agent in the same Redhat Linux box and see whether you could reproduce this in your end in the following day?

Any ETA on the next release with our already made fix? 

Further, after InformixHQ is  running a day,  we noticed the generated Log file with 'nohup' background command output in Linux is considerably big and we would like to completely stop writing all the success output messages but only the errors  to the log file (in our case nohup.out) . Would this be possible with the current version?
  
![2018-05-31 09_50_02-cpu-high - vsphere client](https://user-images.githubusercontent.com/39396150/40756706-4697246e-64c8-11e8-9a40-f2c4fb49f729.png)
[InformixHQ_log.zip](https://github.com/informix/informixhq-agent/files/2056292/InformixHQ_log.zip)

 Thanks

**Comment by ekuehnhausen** [comment]
Can you tell me what JDK you are using? Since I'm not able to reproduce this in house, I'll probably need you to gather some profile information from the JVM. I can send you instructions based on the Java JDK you are using.

Also next time, can you separate out the server and agent log files? Your log file has messages from both the server and agent which makes it harder to track what is going on in the agent.

Next time you run it, can you use this command to turn on timestamps in your log file:
`java -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat="YYYY-MM-dd HH:mm:ss.SSS" -jar informixhq-agent-0.1.0.jar agent.properties`

(This will become the default behavior in the next version of that agent - probably released next week, but the above command will do the same thing on the current release.)

You also asked how to turn off the INFO (success) messages from the log. If you add `-Dorg.slf4j.simpleLogger.defaultLogLevel=WARN` to this command, that would disabled all INFO level logging such that you just got WARN and ERROR messages in the log file.

**Comment by jagathabhaya** [comment]
Thanks for the detail instructions. 
Following lists the java version detail that I am using in one of these servers .

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

BTW:
Once I tried with the provided command for setting-up the agent , it received me the following error ?
Anything , I am doing wrong with the command provided with ?

![2018-06-01 08_58_40-log_error](https://user-images.githubusercontent.com/39396150/40812684-6c96075e-657a-11e8-9409-002e36f52c14.png)

Thanks

**Comment by jagathabhaya** [comment]
My apologies . I could fix the issue . Just ignore my previous error.

I will setup another round of the test and try to collect requested information on two separate log files.

BTW: Do you want to collect the information with or without  'all INFO level logging ' ?

Regards

**Comment by jagathabhaya** [comment]
Hi,

Today morning,  I did a new setup to collect the information for you. When I started the InformixHQ setup and the sensors , the actual user CPU  was less than 1% max limit. 
After few hours when I checked the cpu usage jumped into over 25% mark steadily all the time. No any other user activity in this test box. Only running this InformixHQ server and agent locally.

Herewith attached the agent and server log files and two screen outputs of how the cpu usage looks like now and the actual processes are  running on. Let me know , if you need anything else?

I am pretty sure,  if I keep the box as it is now, in another couple of hours time, the user cpu will be reached  to the maximum 100 % mark. 
And I believe  this is the initial stage of the issue symptoms I have seen on this.


![2018-06-01 16_24_28-informixhq_started_running_hard_now](https://user-images.githubusercontent.com/39396150/40825491-0a6ef914-65bb-11e8-9fae-29d06546f6c1.jpg)
![2018-06-01 16_40_01-qavc processes](https://user-images.githubusercontent.com/39396150/40825495-0aa3e0c0-65bb-11e8-9d0a-686a7dcd595c.jpg)
[agent.pronto.log](https://github.com/informix/informixhq-agent/files/2061353/agent.pronto.log)
[server.pronto.log](https://github.com/informix/informixhq-agent/files/2061354/server.pronto.log)
![2018-06-01 16_45_41-informixhq_sensors](https://user-images.githubusercontent.com/39396150/40825578-52be1506-65bb-11e8-9a22-dadad1962062.jpg)

Kind Regards

**Comment by jagathabhaya** [comment]
Thanks for the feedback.
Could you please let me know the exact download link for jvisualvm based on the java version i am running support with redhat link 7 ?
The reson i asked that is , they looks like having some later version with different name than jvisualvm and could not find the exact verdion i need to download? 
Otherwise,  try to find out the proper free version to be downloaded looks like to be a little bit tricky thing in the web for me?
Thanks

**Comment by jagathabhaya** [comment]
Hi,
I have tried to capture some CPU profiling information through the 'jvisualvm' 1.7 version installed by default in my Linux 7 box. 
I honestly do not know that whether we need 'jvisualvm' 1.8 as 'InformixHQ' tool  supports with JDK 1.8 and above to do this or not.  ( It was running 5-10 min but no CPU profiling info captured)
However, I could not see the profiling information captured properly through the tool but some thread statistics showed me a deadlock type of situation happened. 
So, I thought sharing these information with you to have some idea from your side. 
Do I still need to give a try with 'jvisualvm' 1.8 version to capture the profiling information ? or these thread statistics provide you enough clue with the possible symptom you wish to have ?
Anyway,  as I expected after the weekend the CPU pegged up to 100% in the server while I was collecting these information in this test box today.

See the attached following screen outputs and the thread statistics detail for your further investigation.

![2018-06-04 cpu profiling](https://user-images.githubusercontent.com/39396150/40892738-15a6a1cc-67de-11e8-971d-3d0198d4473e.jpg)
![2018-06-04 cpu usage](https://user-images.githubusercontent.com/39396150/40892739-15d5de10-67de-11e8-80cb-041aa030475b.jpg)
![2018-06-04 no cpu profiling export data](https://user-images.githubusercontent.com/39396150/40892740-1604f362-67de-11e8-8edd-ec55ede205a0.jpg)
[thread_dump1.txt](https://github.com/informix/informixhq-agent/files/2066490/thread_dump1.txt)
[thread_dump2.txt](https://github.com/informix/informixhq-agent/files/2066491/thread_dump2.txt)

Let me know , your thoughts with this.

Thanks

**Comment by jagathabhaya** [comment]
Apologies , Forgotten to be attached the two log files with my last response.
[agent.pronto.zip](https://github.com/informix/informixhq-agent/files/2066501/agent.pronto.zip)
[server.pronto.log](https://github.com/informix/informixhq-agent/files/2066502/server.pronto.log)

**Comment by jagathabhaya** [comment]
Wow...When I checked in half an hours time, I could see some results have been appeared under the profiling screen.  
Attached those detail also for your further reference.

Note: The agent java process also running almost all CPU when I captured these information.

![2018-06-04 top_output](https://user-images.githubusercontent.com/39396150/40897139-84182eb4-67fc-11e8-9458-9b58e5bf2aa1.png)

![2018-06-04_cpu](https://user-images.githubusercontent.com/39396150/40897093-44a003d8-67fc-11e8-8306-a5b799c4bc1a.png)
[cpu-live.zip](https://github.com/informix/informixhq-agent/files/2066766/cpu-live.zip)
![informixhq](https://user-images.githubusercontent.com/39396150/40897094-4504211a-67fc-11e8-9cc3-ff77dea51216.png)

Let me know, Anything else required from my side?

Kind Regards

**Comment by ekuehnhausen** [comment]
I believe we have finally identified the issue. 

Your CPU profiling info points to the agent getting stuck in a couple of functions from the Java-WebSocket library, which is one of our dependencies. After poking through old issues in that library's github repo, I found defects describing similar issues of CPU going to 100% when SSL is enabled. This has been addressed in a newer version of the Java-WebSocket library. So we just need to move the agent to the latest version of the Java-WebSocket library.

This will be done in the next release of InformixHQ (version 0.1.1) which should be out by the end of this week. So please do pull down that release when it's available and let me know if that addresses this problem in your environment.

Also we did notice the deadlock from the JDBC driver that showed up in your stack trace. There is a fix in progress for that, but we'll have to wait for the next JDBC release to pick that up. Luckily though, there is a flag that can be set that will disable the code that causes this deadlock. I will be putting a workaround into InformixHQ to set the necessary flag as a workaround for the time being. This workaround will also be in place for the release that is coming this week.

Thank you so much for your patience in tracking down the issue. And for all of the logging, stack trace, and profiling information you provided us!

**Comment by jagathabhaya** [comment]
That will be a good news for us. Thank you for your fullest support and time with this. 
I really appreciate that.

And also eager to see the next version soon to be tested in our environment ....

As you explained briefly, Please advice me in detail,  how to implement that JDBC driver related workaround solution in the next release?

Hope, You will also investigate and provide me some feedback about the item no 12 (I have opened in the list some time back) for possible InformixHQ enhancements  I would like to be seen in the future release also?

**_One major road block we have is_:**
Lack of the Two Factor authentication support in the application side implementing this in our customer sites as per our company security policy ?

Hope, you will think about this extra security layer requirement also in a next release as well???

Once again,  thank you very much for your prompt support with this.

Kind Regards

**Comment by ekuehnhausen** [comment]
I will build the JDBC workaround into the InformixHQ next build. So no extra steps will be required on your part. This will be a temporary change in InformixHQ that will be reversed when a new JDBC driver with a more permanent fix is available.

To keep things manageable, let's keep this issue confined to the agent CPU problem. I'll respond to your other questions in the corresponding issues.

**Comment by jagathabhaya** [comment]
That would be great. 

Let me know,  once the new release available to be tested in my test servers.

Cheers

**Comment by ekuehnhausen** [comment]
Fixed in version 0.2.0. The binaries for that release have been uploaded and should show up on Maven Central shortly.

**Comment by jagathabhaya** [comment]
Hi 

Apologies for troubling...

I could see the Maven Central has been published a new version of 'jar' for the server. 
But the agent 'jar' is having the same older version . 
Is this correct? 
Do we need to wait till we get the agent latest version to be tested?

Thanks & Regards
![2018-06-08 11_16_34-the central repository search engine_server](https://user-images.githubusercontent.com/39396150/41134068-e753cf06-6b0d-11e8-9f06-ab8cf4376ec4.png)
![2018-06-08 11_17_16-the central repository search engine_agent](https://user-images.githubusercontent.com/39396150/41134069-e7863b44-6b0d-11e8-9626-c404bc92099d.png)

**Comment by ekuehnhausen** [comment]
There should be a version 0.2.0 of the agent as well.  I will check tomorrow and re-upload if necessary. Do wait until the agent version 0.2.0 is available to retest.

**Comment by jagathabhaya** [comment]
Thanks a lot .

 I could not locate the agent version 0.2.0 in the Maven repository yet.

Kind Regards

**Comment by jagathabhaya** [comment]
Thanks. I could find out the version and straight away started my testing.

Let you know,  the issue still exists  or not in next few days.

BTW: Straightaway , when I started to run v2 , I could see following Warning or  Error  message printed in my log file. 
Not sure why? 
![2018-06-08 error_v2 - vsphere client](https://user-images.githubusercontent.com/39396150/41138438-bae3dae4-6b24-11e8-9281-1597ed1f4111.png)
 
Regards

**Comment by jagathabhaya** [comment]
After Little while , I could see the following error message also printed out in the log from V2 agent process.
Not sure why?
![2018-06-08 hq_agent_error1 - vsphere client](https://user-images.githubusercontent.com/39396150/41138982-3a773cb2-6b28-11e8-9536-625e6440174e.png)
![2018-06-08 hq_agent_error2 - vsphere client](https://user-images.githubusercontent.com/39396150/41138983-3aad6468-6b28-11e8-8d96-d9ac7e47c071.png)

**Comment by ekuehnhausen** [comment]
The warning message "Warning! Running the agent as root is not recommended" is just printed because the agent was designed to not need elevated privileges to the system. There is nothing wrong with running it as root, but it is not necessary.

The REST API Exception error: Cannot read system catalog (systables), is caused by an "ISAM error: record is locked" on the database server (ISAM error -107). This error is actually from the InformixHQ server (not the agent) and happened when it was trying to get sensor data for the UI. The UI will continue to poll for data, so if this is a transient error, you probably don't have to worry about it. It if persists though, we'll have to dive more into it.
